### ISSUE TITLE
C++17 migration

### ISSUE THREAD

**Issue by alcjzk** [alcjzk/Webserv#4]
Tracking issue for migrating the project to C++17. Any related tasks can be added here.

- [ ] Use `nullptr` instead of `NULL`
- [ ] Review iterators
- [ ] Replace instances of `throw()` with `noexcept`
- [ ] Utilize `std::system_error` for exceptions with `errno`
