### ISSUE TITLE
Subject checklist

### ISSUE THREAD

**Issue by alcjzk** [alcjzk/Webserv#49]
- [x] Your program has to take a configuration file as argument, or use a default path. #45 
- [x] Your server must never block and the client can be bounced properly if necessary.
- [x] It must be non-blocking and use only 1 poll() (or equivalent) for all the I/O
operations between the client and the server (listen included).lass Server
- [x] poll() (or equivalent) must check read and write at the same time.
- [x] You must never do a read or a write operation without going through poll() (or
equivalent).
- [x] Checking the value of errno is strictly forbidden after a read or a write operation.
- [x] You don’t need to use poll() (or equivalent) before reading your configuration file.
- [x] A request to your server should never hang forever
- [x] Your server must be compatible with the web browser of your choice.
- [x] Your HTTP response status codes must be accurate.
- [x] You server must have default error pages if none are provided.
- [x] You can’t use fork for something else than CGI (like PHP, or Python, and so forth).
- [x] You must be able to serve a fully static website.
- [x] Clients must be able to upload files.
- [x] You need at least GET, POST, and DELETE methods.
- [x] Stress tests your server. It must stay available at all cost.
- [x] Your server must be able to listen to multiple ports (see Configuration file).
- [x] Choose the port and host of each ’server’.
- [x] Setup the server_names or not.
- [x] The first server for a host:port will be the default for this host:port (that means
it will answer to all the requests that don’t belong to an other server).
- [x] Setup default error pages.
- [x] Limit client body size.
- [x] Setup routes with one or multiple of the following rules/configuration (routes wont be using regexp):
 - [x] Define a list of accepted HTTP methods for the route.
 - [x] Define a HTTP redirection.
 - [x] Define a directory or a file from where the file should be searched (for example,
 - [x] Turn on or off directory listing.
- [x] Set a default file to answer if the request is a directory.
- [x] Execute CGI based on certain file extension (for example .php).
- [x] Make it work with POST and GET methods.
- [x] Make the route able to accept uploaded files and configure where they should be saved.
- [x] Because you won’t call the CGI directly, use the full path as PATH_INFO.
- [x] Just remember that, for chunked request, your server needs to unchunk it, the CGI will expect EOF as end of the body.
- [x] Same things for the output of the CGI. If no content_length is returned from the CGI, EOF will mark the end of the returned data.
- [x] Your program should call the CGI with the file requested as first argument.
- [x] The CGI should be run in the correct directory for relative path file access.
- [x] Your server should work with one CGI (php-CGI, Python, and so forth).
- [x] You must provide some configuration files and default basic files to test and demonstrate every feature works during evaluation.
- [x] The important thing is resilience. Your server should never die.
- [x] Do not test with only one program. Write your tests with a more convenient language such as Python or Golang, and so forth. Even in C or C++ if you want to.
