### ISSUE TITLE
Compliance: RFC 9112 2.2 Message Parsing

### ISSUE THREAD

**Issue by alcjzk** [alcjzk/Webserv#9]
### Requirements:

- [x] A sender **MUST NOT** generate a bare CR (a CR character not immediately followed by LF) within any protocol elements other than the content.
  - Requires integration testing

- [x] A recipient of such a bare CR MUST consider that element to be invalid or replace each bare CR with SP before processing the element or forwarding the message. #13
- [x] A sender **MUST NOT** send whitespace between the start-line and the first header field.
  - Requires integration testing

- [x] A recipient that receives whitespace between the start-line and the first header field **MUST** either reject the message as invalid or consume each whitespace-preceded line without further processing of it (i.e., ignore the entire line, along with any subsequent lines preceded by whitespace, until a properly formed header field is received or the header section is terminated).
  - Requires integration testing

- [x] A recipient **MUST** parse an HTTP message as a sequence of octets in an encoding that is a superset of US-ASCII.
  - Trivial as long as locale is not changed at runtime.
---
### Good Practice:
- [x] When a server listening only for HTTP request messages, or processing what appears from the start-line to be an HTTP request message, receives a sequence of octets that does not match the HTTP-message grammar aside from the robustness exceptions listed above, the server **SHOULD** respond with a 400 (Bad Request) response and close the connection.
- [x] Although the line terminator for the start-line and fields is the sequence CRLF, a recipient **MAY** recognize a single LF as a line terminator and ignore any preceding CR.
- [x] In the interest of robustness, a server that is expecting to receive and parse a request-line **SHOULD** ignore at least one empty line (CRLF) received prior to the request-line.
